import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from bson import ObjectId
from datetime import datetime

from repositories import insert_sample_books

MONGO_DETAILS = "mongodb+srv://knowledgetekhub:bBGTHGWYwvsO5ot3@bookdb.2twhiug.mongodb.net/?retryWrites=true&w=majority&appName=bookdb"

# Initialize the MongoDB client
client = AsyncIOMotorClient(MONGO_DETAILS)

# Define the database and collection you want to use
database = client.bookdb
books_collection = database.get_collection("books")


sample_books = [
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "published_date": datetime(1960, 7, 11),
        "text": "A gripping and heart-wrenching story about racial injustice in the Deep South.",
        "genre": "Fiction",
        "publisher": "J.B. Lippincott & Co.",
        "publication_date": datetime(1960, 7, 11),
        "isbn": "978-0-06-112008-4",
        "page_count": 281,
        "language": "English",
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "published_date": datetime(1949, 6, 8),
        "text": "A dystopian novel about the dangers of totalitarianism.",
        "genre": "Dystopian Fiction",
        "publisher": "Secker & Warburg",
        "publication_date": datetime(1949, 6, 8),
        "isbn": "978-0-452-28423-4",
        "page_count": 328,
        "language": "English",
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "published_date": datetime(1813, 1, 28),
        "text": "A romantic novel that also critiques the British landed gentry at the end of the 18th century.",
        "genre": "Romance",
        "publisher": "T. Egerton",
        "publication_date": datetime(1813, 1, 28),
        "isbn": "978-0-19-953556-9",
        "page_count": 279,
        "language": "English",
    },
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "published_date": datetime(1925, 4, 10),
        "text": "A novel about the American Dream and the disillusionment that comes with it.",
        "genre": "Classic",
        "publisher": "Scribner",
        "publication_date": datetime(1925, 4, 10),
        "isbn": "978-0-7432-7356-5",
        "page_count": 180,
        "language": "English",
    },
    {
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "published_date": datetime(1851, 10, 18),
        "text": "The narrative of Captain Ahab's obsessive quest to seek revenge on the white whale.",
        "genre": "Adventure",
        "publisher": "Harper & Brothers",
        "publication_date": datetime(1851, 10, 18),
        "isbn": "978-0-14-243724-7",
        "page_count": 585,
        "language": "English",
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "published_date": datetime(1951, 7, 16),
        "text": "A story about adolescent alienation and loss of innocence in American society.",
        "genre": "Fiction",
        "publisher": "Little, Brown and Company",
        "publication_date": datetime(1951, 7, 16),
        "isbn": "978-0-316-76948-0",
        "page_count": 214,
        "language": "English",
    },
    {
        "title": "The Lord of the Rings",
        "author": "J.R.R. Tolkien",
        "published_date": datetime(1954, 7, 29),
        "text": "An epic fantasy tale of the quest to destroy the One Ring and defeat the Dark Lord Sauron.",
        "genre": "Fantasy",
        "publisher": "Allen & Unwin",
        "publication_date": datetime(1954, 7, 29),
        "isbn": "978-0-618-00222-8",
        "page_count": 1216,
        "language": "English",
    },
    {
        "title": "Jane Eyre",
        "author": "Charlotte Brontë",
        "published_date": datetime(1847, 10, 16),
        "text": "A story of a young woman's journey to self-discovery and her struggles with morality, religion, and social class.",
        "genre": "Romance",
        "publisher": "Smith, Elder & Co.",
        "publication_date": datetime(1847, 10, 16),
        "isbn": "978-0-14-144114-6",
        "page_count": 532,
        "language": "English",
    },
    {
        "title": "War and Peace",
        "author": "Leo Tolstoy",
        "published_date": datetime(1869, 1, 1),
        "text": "A historical novel that intertwines the lives of families during the Napoleonic Wars.",
        "genre": "Historical Fiction",
        "publisher": "The Russian Messenger",
        "publication_date": datetime(1869, 1, 1),
        "isbn": "978-0-14-303999-0",
        "page_count": 1392,
        "language": "English",
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "published_date": datetime(1937, 9, 21),
        "text": "A prelude to The Lord of the Rings, following Bilbo Baggins' adventure.",
        "genre": "Fantasy",
        "publisher": "George Allen & Unwin",
        "publication_date": datetime(1937, 9, 21),
        "isbn": "978-0-618-00221-1",
        "page_count": 310,
        "language": "English",
    },
    {
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "published_date": datetime(1866, 1, 1),
        "text": "A psychological exploration of guilt and redemption.",
        "genre": "Psychological Fiction",
        "publisher": "The Russian Messenger",
        "publication_date": datetime(1866, 1, 1),
        "isbn": "978-0-14-044913-6",
        "page_count": 430,
        "language": "English",
    },
    {
        "title": "The Odyssey",
        "author": "Homer",
        "published_date": datetime(1877, 1, 1),
        "text": "The epic journey of Odysseus as he returns home after the Trojan War.",
        "genre": "Epic",
        "publisher": "William Heinemann",
        "publication_date": datetime(1877, 1, 1),
        "isbn": "978-0-14-026886-7",
        "page_count": 560,
        "language": "English",
    },
    {
        "title": "The Brothers Karamazov",
        "author": "Fyodor Dostoevsky",
        "published_date": datetime(1880, 1, 1),
        "text": "A philosophical novel exploring themes of faith, doubt, and free will.",
        "genre": "Philosophical Fiction",
        "publisher": "The Russian Messenger",
        "publication_date": datetime(1880, 1, 1),
        "isbn": "978-0-14-044924-2",
        "page_count": 796,
        "language": "English",
    },
    {
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "published_date": datetime(1932, 1, 1),
        "text": "A dystopian society that emphasizes science and technology over individual freedom.",
        "genre": "Dystopian Fiction",
        "publisher": "Chatto & Windus",
        "publication_date": datetime(1932, 1, 1),
        "isbn": "978-0-06-085052-4",
        "page_count": 268,
        "language": "English",
    },
    {
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "published_date": datetime(1847, 12, 1),
        "text": "A tale of passion and revenge on the English moors.",
        "genre": "Gothic Fiction",
        "publisher": "Thomas Cautley Newby",
        "publication_date": datetime(1847, 12, 1),
        "isbn": "978-0-14-143955-6",
        "page_count": 416,
        "language": "English",
    },
    {
        "title": "The Divine Comedy",
        "author": "Dante Alighieri",
        "published_date": datetime(1320, 1, 1),
        "text": "An epic poem depicting the journey through Hell, Purgatory, and Heaven.",
        "genre": "Epic Poetry",
        "publisher": "N/A",
        "publication_date": datetime(1320, 1, 1),
        "isbn": "978-0-19-953564-4",
        "page_count": 798,
        "language": "Italian",
    },
    {
        "title": "Les Misérables",
        "author": "Victor Hugo",
        "published_date": datetime(1862, 1, 1),
        "text": "A tale of justice and redemption in post-revolutionary France.",
        "genre": "Historical Fiction",
        "publisher": "A. Lacroix, Verboeckhoven & Cie",
        "publication_date": datetime(1862, 1, 1),
        "isbn": "978-0-14-044430-1",
        "page_count": 1232,
        "language": "French",
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "published_date": datetime(1951, 7, 16),
        "text": "A story about adolescent alienation and loss of innocence.",
        "genre": "Fiction",
        "publisher": "Little, Brown and Company",
        "publication_date": datetime(1951, 7, 16),
        "isbn": "978-0-316-76948-0",
        "page_count": 214,
        "language": "English",
    },
    {
        "title": "Don Quixote",
        "author": "Miguel de Cervantes",
        "published_date": datetime(1605, 1, 1),
        "text": "A novel about the adventures of a man who becomes a self-styled knight.",
        "genre": "Novel",
        "publisher": "Francisco de Robles",
        "publication_date": datetime(1605, 1, 1),
        "isbn": "978-0-14-243723-0",
        "page_count": 1072,
        "language": "Spanish",
    },
    {
        "title": "Dracula",
        "author": "Bram Stoker",
        "published_date": datetime(1897, 5, 26),
        "text": "A Gothic horror novel about the infamous vampire Count Dracula.",
        "genre": "Horror",
        "publisher": "Archibald Constable and Company",
        "publication_date": datetime(1897, 5, 26),
        "isbn": "978-0-14-143984-6",
        "page_count": 416,
        "language": "English",
    },
    {
        "title": "The Picture of Dorian Gray",
        "author": "Oscar Wilde",
        "published_date": datetime(1890, 6, 20),
        "text": "A novel about a man who remains young while his portrait ages.",
        "genre": "Philosophical Fiction",
        "publisher": "Lippincott's Monthly Magazine",
        "publication_date": datetime(1890, 6, 20),
        "isbn": "978-0-14-143957-1",
        "page_count": 254,
        "language": "English",
    },
    {
        "title": "The Chronicles of Narnia",
        "author": "C.S. Lewis",
        "published_date": datetime(1950, 10, 16),
        "text": "A series of seven fantasy novels set in the magical land of Narnia.",
        "genre": "Fantasy",
        "publisher": "Geoffrey Bles",
        "publication_date": datetime(1950, 10, 16),
        "isbn": "978-0-06-623850-0",
        "page_count": 768,
        "language": "English",
    },
    {
        "title": "A Tale of Two Cities",
        "author": "Charles Dickens",
        "published_date": datetime(1859, 4, 30),
        "text": "A historical novel set during the French Revolution.",
        "genre": "Historical Fiction",
        "publisher": "Chapman & Hall",
        "publication_date": datetime(1859, 4, 30),
        "isbn": "978-0-14-143960-1",
        "page_count": 341,
        "language": "English",
    },
    {
        "title": "Gone with the Wind",
        "author": "Margaret Mitchell",
        "published_date": datetime(1936, 6, 30),
        "text": "A novel about the American South during the Civil War and Reconstruction.",
        "genre": "Historical Fiction",
        "publisher": "Macmillan Publishers",
        "publication_date": datetime(1936, 6, 30),
        "isbn": "978-1-4165-6374-0",
        "page_count": 1037,
        "language": "English",
    },
    {
        "title": "The Hitchhiker's Guide to the Galaxy",
        "author": "Douglas Adams",
        "published_date": datetime(1979, 10, 12),
        "text": "A comedic science fiction series about the misadventures of Arthur Dent.",
        "genre": "Science Fiction",
        "publisher": "Pan Books",
        "publication_date": datetime(1979, 10, 12),
        "isbn": "978-0-345-39180-3",
        "page_count": 216,
        "language": "English",
    },
    {
        "title": "The Shining",
        "author": "Stephen King",
        "published_date": datetime(1977, 1, 28),
        "text": "A horror novel about a family staying in a haunted hotel.",
        "genre": "Horror",
        "publisher": "Doubleday",
        "publication_date": datetime(1977, 1, 28),
        "isbn": "978-0-385-12167-5",
        "page_count": 447,
        "language": "English",
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "published_date": datetime(1988, 1, 1),
        "text": "A novel about a shepherd's journey to find his personal legend.",
        "genre": "Adventure",
        "publisher": "Rocco",
        "publication_date": datetime(1988, 1, 1),
        "isbn": "978-0-06-231500-7",
        "page_count": 208,
        "language": "Portuguese",
    },
    {
        "title": "The Road",
        "author": "Cormac McCarthy",
        "published_date": datetime(2006, 9, 26),
        "text": "A post-apocalyptic novel about a father and son's struggle for survival.",
        "genre": "Dystopian Fiction",
        "publisher": "Alfred A. Knopf",
        "publication_date": datetime(2006, 9, 26),
        "isbn": "978-0-307-26547-0",
        "page_count": 287,
        "language": "English",
    },
    {
        "title": "Beloved",
        "author": "Toni Morrison",
        "published_date": datetime(1987, 9, 16),
        "text": "A novel about an escaped slave haunted by her past.",
        "genre": "Historical Fiction",
        "publisher": "Alfred A. Knopf",
        "publication_date": datetime(1987, 9, 16),
        "isbn": "978-0-345-40289-4",
        "page_count": 324,
        "language": "English",
    },
    {
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "published_date": datetime(1985, 9, 19),
        "text": "A dystopian novel about a totalitarian regime that subjugates women.",
        "genre": "Dystopian Fiction",
        "publisher": "McClelland and Stewart",
        "publication_date": datetime(1985, 9, 19),
        "isbn": "978-0-385-49344-6",
        "page_count": 311,
        "language": "English",
    },
    {
        "title": "Little Women",
        "author": "Louisa May Alcott",
        "published_date": datetime(1868, 9, 30),
        "text": "A novel about the lives, loves, and struggles of the March sisters.",
        "genre": "Coming-of-Age",
        "publisher": "Roberts Brothers",
        "publication_date": datetime(1868, 9, 30),
        "isbn": "978-0-14-751401-2",
        "page_count": 759,
        "language": "English",
    },
    {
        "title": "A Prayer for Owen Meany",
        "author": "John Irving",
        "published_date": datetime(1989, 9, 15),
        "text": "A novel about a young man whose life is changed by an extraordinary friend.",
        "genre": "Historical Fiction",
        "publisher": "William Morrow and Company",
        "publication_date": datetime(1989, 9, 15),
        "isbn": "978-0-688-09786-5",
        "page_count": 633,
        "language": "English",
    },
    {
        "title": "The Outsiders",
        "author": "S.E. Hinton",
        "published_date": datetime(1967, 4, 24),
        "text": "A story about the conflict between two teenage gangs in the 1960s.",
        "genre": "Young Adult",
        "publisher": "Viking Press",
        "publication_date": datetime(1967, 4, 24),
        "isbn": "978-0-14-038572-4",
        "page_count": 180,
        "language": "English",
    },
    {
        "title": "The Color Purple",
        "author": "Alice Walker",
        "published_date": datetime(1982, 7, 1),
        "text": "A novel about the life of African American women in the early 20th century.",
        "genre": "Historical Fiction",
        "publisher": "Harcourt Brace Jovanovich",
        "publication_date": datetime(1982, 7, 1),
        "isbn": "978-0-15-602835-8",
        "page_count": 295,
        "language": "English",
    },
    {
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "published_date": datetime(2003, 5, 29),
        "text": "A story about a young boy from Afghanistan and his complicated relationship with his friend.",
        "genre": "Contemporary Fiction",
        "publisher": "Riverhead Books",
        "publication_date": datetime(2003, 5, 29),
        "isbn": "978-1-59448-000-3",
        "page_count": 371,
        "language": "English",
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "published_date": datetime(2011, 9, 4),
        "text": "A book that explores the history of the human species from the Stone Age to the present.",
        "genre": "Non-Fiction",
        "publisher": "Harvill Secker",
        "publication_date": datetime(2011, 9, 4),
        "isbn": "978-0-06-231611-0",
        "page_count": 443,
        "language": "English",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "published_date": datetime(2018, 2, 20),
        "text": "A memoir about a woman who grows up in a strict and abusive household in rural Idaho and her journey to education.",
        "genre": "Memoir",
        "publisher": "Random House",
        "publication_date": datetime(2018, 2, 20),
        "isbn": "978-0-399-59050-4",
        "page_count": 334,
        "language": "English",
    },
    {
        "title": "The Goldfinch",
        "author": "Donna Tartt",
        "published_date": datetime(2013, 10, 22),
        "text": "A novel about a young boy who survives an explosion at an art museum and his troubled life that follows.",
        "genre": "Literary Fiction",
        "publisher": "Little, Brown and Company",
        "publication_date": datetime(2013, 10, 22),
        "isbn": "978-0-316-27162-6",
        "page_count": 771,
        "language": "English",
    },
    {
        "title": "The Silmarillion",
        "author": "J.R.R. Tolkien",
        "published_date": datetime(1977, 9, 15),
        "text": "A collection of mythopoeic stories that form the background to The Lord of the Rings.",
        "genre": "Fantasy",
        "publisher": "Allen & Unwin",
        "publication_date": datetime(1977, 9, 15),
        "isbn": "978-0-618-00221-1",
        "page_count": 365,
        "language": "English",
    },
    {
        "title": "The Secret Garden",
        "author": "Frances Hodgson Burnett",
        "published_date": datetime(1911, 8, 1),
        "text": "A children's novel about a young orphan who discovers a neglected garden and brings it back to life.",
        "genre": "Children's Fiction",
        "publisher": "Frederick A. Stokes Company",
        "publication_date": datetime(1911, 8, 1),
        "isbn": "978-0-14-751402-9",
        "page_count": 331,
        "language": "English",
    },
    {
        "title": "The Sun Also Rises",
        "author": "Ernest Hemingway",
        "published_date": datetime(1926, 10, 22),
        "text": "A novel about a group of American expatriates traveling from Paris to Pamplona to watch the bullfights.",
        "genre": "Modernist Fiction",
        "publisher": "Scribner",
        "publication_date": datetime(1926, 10, 22),
        "isbn": "978-0-684-80173-1",
        "page_count": 251,
        "language": "English",
    },
    {
        "title": "A Wrinkle in Time",
        "author": "Madeleine L'Engle",
        "published_date": datetime(1962, 1, 1),
        "text": "A science fantasy novel about a girl who travels through time and space to rescue her father.",
        "genre": "Science Fiction",
        "publisher": "Farrar, Straus and Giroux",
        "publication_date": datetime(1962, 1, 1),
        "isbn": "978-0-374-33277-9",
        "page_count": 232,
        "language": "English",
    },
    {
        "title": "The Little Prince",
        "author": "Antoine de Saint-Exupéry",
        "published_date": datetime(1943, 4, 6),
        "text": "A philosophical tale about a young prince's journey through the universe.",
        "genre": "Novella",
        "publisher": "Reynal & Hitchcock",
        "publication_date": datetime(1943, 4, 6),
        "isbn": "978-0-15-601398-7",
        "page_count": 96,
        "language": "French",
    },
    {
        "title": "The Martian",
        "author": "Andy Weir",
        "published_date": datetime(2011, 2, 11),
        "text": "A novel about an astronaut stranded on Mars and his struggle to survive.",
        "genre": "Science Fiction",
        "publisher": "Crown Publishing Group",
        "publication_date": datetime(2011, 2, 11),
        "isbn": "978-0-553-80561-7",
        "page_count": 369,
        "language": "English",
    },
    {
        "title": "Dune",
        "author": "Frank Herbert",
        "published_date": datetime(1965, 8, 1),
        "text": "A science fiction epic set in a distant future amidst a huge interstellar empire.",
        "genre": "Science Fiction",
        "publisher": "Chilton Books",
        "publication_date": datetime(1965, 8, 1),
        "isbn": "978-0-441-17271-9",
        "page_count": 412,
        "language": "English",
    },
]


# Function to insert sample books into the database
async def insert_sample_books():
    try:
        await books_collection.insert_many(sample_books)
        print("Sample books inserted successfully.")
    except Exception as e:
        print(f"An error occurred while inserting sample books: {e}")


# Main function to run the async function
def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(insert_sample_books())


if __name__ == "__main__":
    main()
